use crate::config::Config;
use crate::fs::Project;
use crate::rules::common::{is_test_file, is_ts_source_file, join};
use crate::rules::{Report, Rule};
use crate::structured::parse_json;

pub struct OpenApiContractsRule;

impl Rule for OpenApiContractsRule {
    fn id(&self) -> &'static str {
        "openapi-contracts"
    }

    fn category(&self) -> &'static str {
        "api"
    }

    fn description(&self) -> &'static str {
        "keeps generated OpenAPI contracts in the canonical client location"
    }

    fn check(&self, project: &Project, config: &Config, report: &mut Report) {
        for app_root in &config.web_apps {
            check_generated_file(project, app_root, report, self.id());
            check_package_script(project, app_root, report, self.id());
        }

        for file in &project.files {
            if !is_ts_source_file(&file.rel_path) || is_test_file(&file.rel_path) {
                continue;
            }
            let Some(analysis) = &file.ts else {
                continue;
            };
            for import in &analysis.imports {
                if is_generated_api_specifier(&import.source)
                    && !file.rel_path.ends_with("src/lib/api/client.ts")
                {
                    report.error(
                        self.id(),
                        &file.rel_path,
                        Some(import.line),
                        "generated OpenAPI types are imported outside the API client wrapper",
                        "Import fetchClient/useApiQuery/useApiMutation from src/lib/api/client.ts instead. src/lib/api/v1.d.ts is generated plumbing and should only feed the client wrapper; refresh it with `pnpm gen:api`.",
                    );
                }
            }
        }
    }
}

fn check_generated_file(
    project: &Project,
    app_root: &str,
    report: &mut Report,
    rule_id: &'static str,
) {
    let canonical = join(app_root, "src/lib/api/v1.d.ts");
    if project.exists(&join(app_root, "src/server/api/index.ts")) && !project.exists(&canonical) {
        report.error(
            rule_id,
            canonical.clone(),
            None,
            "generated OpenAPI paths type is missing",
            "Generate it at src/lib/api/v1.d.ts. Install with `pnpm add -D openapi-typescript`, expose /api/v1/openapi.json from the Hono OpenAPI app, then run `pnpm gen:api`.",
        );
    }

    if project.exists(&canonical) {
        let text = project.read(&canonical).unwrap_or_default();
        if !text.contains("This file was auto-generated by openapi-typescript") {
            report.error(
                rule_id,
                canonical,
                None,
                "generated OpenAPI file is missing the openapi-typescript header",
                "Do not hand-maintain this file. Regenerate it with `pnpm gen:api`; the command should invoke openapi-typescript and write src/lib/api/v1.d.ts.",
            );
        }
    }

    for legacy in [
        join(app_root, "src/schemas/api/api.gen.d.ts"),
        join(app_root, "src/schemas/api/api.gen.ts"),
    ] {
        if project.exists(&legacy) {
            report.error(
                rule_id,
                legacy,
                None,
                "generated API types are in a non-canonical location",
                "Move generated OpenAPI types to src/lib/api/v1.d.ts and import them only from src/lib/api/client.ts.",
            );
        }
    }
}

fn check_package_script(
    project: &Project,
    app_root: &str,
    report: &mut Report,
    rule_id: &'static str,
) {
    let package_path = join(app_root, "package.json");
    let Some(package_json) = project.read(&package_path) else {
        return;
    };
    let Some(script) = gen_api_script(package_json) else {
        report.error(
            rule_id,
            package_path,
            None,
            "package.json is missing gen:api",
            "Add a script such as `\"gen:api\": \"openapi-typescript http://localhost:3000/api/v1/openapi.json -o src/lib/api/v1.d.ts\"` and install it with `pnpm add -D openapi-typescript`.",
        );
        return;
    };
    if !script.contains("openapi-typescript") && !script.contains("gen-api") {
        report.error(
            rule_id,
            package_path,
            None,
            "gen:api does not appear to run openapi-typescript",
            "Use openapi-typescript directly or call a project script that invokes it. Install with `pnpm add -D openapi-typescript`.",
        );
    }
}

fn gen_api_script(package_json: &str) -> Option<String> {
    parse_json(package_json)
        .ok()?
        .get("scripts")?
        .get("gen:api")?
        .as_str()
        .map(str::to_string)
}

fn is_generated_api_specifier(specifier: &str) -> bool {
    specifier.ends_with("/lib/api/v1")
        || matches!(specifier, "~/lib/api/v1" | "@/lib/api/v1" | "./v1")
}

#[cfg(test)]
mod tests {
    use super::gen_api_script;

    #[test]
    fn reads_only_the_structured_gen_api_script() {
        let package = r#"{
          "description": "openapi-typescript is mentioned here",
          "scripts": { "gen:api": "pnpm exec openapi-typescript spec.json -o src/lib/api/v1.d.ts" }
        }"#;
        assert_eq!(
            gen_api_script(package),
            Some("pnpm exec openapi-typescript spec.json -o src/lib/api/v1.d.ts".to_string())
        );
        assert_eq!(gen_api_script(r#"{"description":"gen:api"}"#), None);
    }
}
