use crate::config::Config;
use crate::fs::Project;
use crate::rules::{Report, Rule};

pub struct SourceIntegrityRule;

impl Rule for SourceIntegrityRule {
    fn id(&self) -> &'static str {
        "source-integrity"
    }

    fn category(&self) -> &'static str {
        "quality"
    }

    fn description(&self) -> &'static str {
        "requires parseable TypeScript, generated-file provenance, and justified type-check escapes"
    }

    fn check(&self, project: &Project, _config: &Config, report: &mut Report) {
        for file in &project.files {
            if let Some(ts) = &file.ts
                && let Some(error) = ts.parse_errors.first()
            {
                report.error(
                    self.id(),
                    &file.rel_path,
                    None,
                    "TypeScript source could not be parsed for structural analysis",
                    format!(
                        "fix the syntax error before relying on ultralint; the parser reported: {error}"
                    ),
                );
            }

            if file.generated {
                check_generated_provenance(file, report, self.id());
                continue;
            }

            for (index, line) in file.text.lines().enumerate() {
                let trimmed = line.trim();
                if trimmed.contains("@ts-nocheck") || trimmed.contains("@ts-ignore") {
                    report.error(
                        self.id(),
                        &file.rel_path,
                        Some(index + 1),
                        "unchecked TypeScript suppression is not allowed",
                        "remove @ts-nocheck/@ts-ignore and fix the type boundary. For a temporary compiler-specific exception, use @ts-expect-error with a concrete explanation and an ultralint suppression expiry.",
                    );
                }
                if trimmed.contains("@ts-expect-error")
                    && !trimmed.contains(" -- ")
                    && !trimmed.contains(": ")
                {
                    report.error(
                        self.id(),
                        &file.rel_path,
                        Some(index + 1),
                        "@ts-expect-error is missing a reason",
                        "append a concrete reason, for example `// @ts-expect-error -- upstream type is incomplete`, and remove it when the upstream issue is fixed",
                    );
                }
                if trimmed.contains("biome-ignore") && !trimmed.contains(": ") {
                    report.error(
                        self.id(),
                        &file.rel_path,
                        Some(index + 1),
                        "Biome suppression is missing a reason",
                        "use Biome's reason form, such as `// biome-ignore lint/<rule>: concrete reason`, and keep the exception local",
                    );
                }
            }
        }
    }
}

fn check_generated_provenance(
    file: &crate::fs::ProjectFile,
    report: &mut Report,
    rule_id: &'static str,
) {
    let expected_marker = if file.rel_path.ends_with("routeTree.gen.ts") {
        Some("generated by TanStack Router")
    } else if file.rel_path.ends_with("worker-configuration.d.ts") {
        Some("Generated by Wrangler")
    } else if file.rel_path.ends_with("src/lib/api/v1.d.ts") {
        Some("auto-generated by openapi-typescript")
    } else if file.rel_path.contains(".gen.") {
        Some("generated")
    } else {
        None
    };
    let Some(marker) = expected_marker else {
        return;
    };
    if file
        .text
        .to_ascii_lowercase()
        .contains(&marker.to_ascii_lowercase())
    {
        return;
    }
    report.error(
        rule_id,
        &file.rel_path,
        None,
        "generated-looking file has no recognized generator provenance",
        "regenerate this artifact with its canonical pnpm gen:* command. Do not rename handwritten files to .gen.ts or .d.ts to bypass source policy.",
    );
}
